require 'bookest.plugins.cmp'
require 'bookest.plugins.gitsigns'
require 'bookest.plugins.harpoon'
require 'bookest.plugins.lualine'
require 'bookest.plugins.telescope'
require 'bookest.plugins.treesitter'
